import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from sqlalchemy.orm import Session
from app.models import RFP

# Directory to save generated files
OUTPUT_DIR = "/app/data/generated_proposals"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def generate_proposal_ppt(rfp_id: int, db: Session):
    # 1. Fetch Data
    rfp = db.query(RFP).filter(RFP.id == rfp_id).first()
    if not rfp:
        return {"error": "RFP not found"}
    
    data = rfp.extracted_data
    if not data or "match" not in data or "pricing" not in data:
        return {"error": "RFP data incomplete. Run Technical & Pricing agents first."}

    match_data = data["match"]
    pricing_data = data["pricing"]
        
    raw_reqs = data.get("requirements", {})
        
    if isinstance(raw_reqs, list):
        if len(raw_reqs) > 0 and isinstance(raw_reqs[0], dict):
            reqs = raw_reqs[0]
        else:
            reqs = {
                    "material_type": ", ".join([str(x) for x in raw_reqs]), 
                    "dft_requirement": "See detailed specs",
                    "application_method": "Standard"
                }
    else:
            reqs = raw_reqs
        

    # 2. Create Presentation
    prs = Presentation()

    # --- SLIDE 1: TITLE SLIDE ---
    slide_layout = prs.slide_layouts[0] # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = f"Proposal for {rfp.client_name}"
    subtitle.text = f"Ref: {rfp.title}\nGenerated by BidWin AI"

    # --- SLIDE 2: EXECUTIVE SUMMARY ---
    slide_layout = prs.slide_layouts[1] # Title and Content
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Executive Summary"
    
    # Add text box
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Based on our analysis of your tender document, we propose the following high-performance solution:"
    
    p = tf.add_paragraph()
    p.text = f"• Identified Need: {reqs.get('material_type', 'Industrial Coating')}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Proposed Solution: {match_data['product_id']} - {pricing_data['product_name']}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Match Confidence: {match_data.get('match_score', 'N/A')}%"
    p.level = 1

    # --- SLIDE 3: TECHNICAL MATCH ---
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Technical Specification Match"
    
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Our solution meets or exceeds your technical requirements:"
    
    p = tf.add_paragraph()
    p.text = f"• Requirement (DFT): {reqs.get('dft_requirement', 'Standard')}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Our Specification: {pricing_data['product_name']} is optimized for this range."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Application Method: Compatible with {reqs.get('application_method', 'standard methods')}."
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Reason for Selection: {match_data.get('reason', 'Best technical fit')}."
    p.level = 1

    # --- SLIDE 4: COMMERCIAL PROPOSAL ---
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Commercial Proposal"
    
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Pricing Breakdown (Per Unit):"
    
    comps = pricing_data['components']
    
    p = tf.add_paragraph()
    p.text = f"• Base Price: ₹ {comps['base_price']}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• Logistics (5%): ₹ {comps['logistics_5_percent']}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• GST (18%): ₹ {comps['gst_18_percent']}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"• TOTAL UNIT PRICE: ₹ {pricing_data['final_unit_price']}"
    p.font.bold = True
    p.font.size = Pt(24)
    p.level = 0

    # 3. Save File
    filename = f"proposal_{rfp_id}.pptx"
    file_path = os.path.join(OUTPUT_DIR, filename)
    prs.save(file_path)

    # 4. Update DB
    rfp.status = "Ready to Submit"
    db.commit()

    return {
        "status": "success",
        "file_url": file_path,
        "download_url": f"/api/agents/main/download/{filename}"
    }